#!/usr/bin/env zsh
# tms: fzf switch tmux session
emulate -L zsh

local session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --prompt="Switch to: ")
[[ -n "$session" ]] && tma "$session"
