#!/usr/bin/env python3
"""
Claude Code hook to block self-attribution patterns in git commits and GitHub PRs/issues.

Blocks specific attribution patterns while allowing legitimate mentions of "Claude".

Exit codes:
  0 - Allow the command
  2 - Block the command (with error message to stderr)
"""

import json
import re
import sys

# Patterns that indicate self-attribution in commits
COMMIT_PATTERNS = [
    r"Co-Authored-By:.*[Cc]laude",
    r"Co-Authored-By:.*[Aa]nthropic",
    r"Co-Authored-By:.*noreply@anthropic",
]

# Patterns that indicate self-attribution in PRs/issues
GH_PATTERNS = [
    r"Generated with.*Claude",
    r"Generated by Claude",
    r"\U0001F916.*Claude Code",  # Robot emoji
]


def check_git_commit(command: str) -> str | None:
    """Check if a git commit command contains blocked attribution patterns."""
    if not re.search(r"\b(git|dotfiles)\b.*\bcommit\b", command):
        return None

    for pattern in COMMIT_PATTERNS:
        if re.search(pattern, command, re.IGNORECASE):
            return f"Blocked: Self-attribution pattern detected: {pattern}"

    return None


def check_gh_command(command: str) -> str | None:
    """Check if a gh command contains blocked attribution patterns."""
    if not re.search(r"\bgh\s+(pr|issue)\s+(create|edit|comment)", command):
        return None

    for pattern in GH_PATTERNS:
        if re.search(pattern, command, re.IGNORECASE):
            return f"Blocked: Self-attribution pattern detected: {pattern}"

    return None


def main() -> int:
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        # Can't parse input, allow by default
        return 0

    tool_input = input_data.get("tool_input", {})
    command = tool_input.get("command", "")

    if not command:
        return 0

    # Check for blocked patterns
    for checker in [check_git_commit, check_gh_command]:
        if error := checker(command):
            print(error, file=sys.stderr)
            return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
