#!/usr/bin/env python3
"""
Claude Code hook to block self-attribution patterns in git commits and GitHub PRs/issues.

Blocks specific attribution patterns while allowing legitimate mentions of "Claude".

Exit codes:
  0 - Allow the command
  2 - Block the command (with error message to stderr)

Tests: uv run --with pytest pytest ~/.claude/hooks/test_no_self_attribution.py -v
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Patterns that indicate self-attribution in commits
COMMIT_PATTERNS = [
    r"Co-Authored-By:.*[Cc]laude",
    r"Co-Authored-By:.*[Aa]nthropic",
    r"Co-Authored-By:.*noreply@anthropic",
]

# Patterns that indicate self-attribution in PRs/issues
GH_PATTERNS = [
    r"Generated with.*Claude",
    r"Generated by Claude",
    r"\U0001F916.*Claude Code",  # Robot emoji
]


def _check_patterns_in_text(text: str, patterns: list[str]) -> str | None:
    """Return first matching pattern found in text, or None."""
    for pattern in patterns:
        if re.search(pattern, text, re.IGNORECASE):
            return pattern
    return None


def _read_file_arg(command: str, flag_pattern: str) -> str | None:
    """Extract and read content from a file referenced by a CLI flag."""
    match = re.search(flag_pattern, command)
    if not match:
        return None
    try:
        return Path(match.group(1)).expanduser().read_text()
    except (OSError, ValueError):
        return None


# NOTE: A commit bypassed this hook in Jan 2025 — root cause unclear
# (conversation context was compacted). Adding -F file checks as defence in depth.


def check_git_commit(command: str) -> str | None:
    """Check if a git commit command contains blocked attribution patterns."""
    if not re.search(r"\b(git|dotfiles)\b.*\bcommit\b", command):
        return None

    # Check command string itself
    if p := _check_patterns_in_text(command, COMMIT_PATTERNS):
        return f"Blocked: Self-attribution pattern detected: {p}"

    # Check -F / --file referenced commit message file
    content = _read_file_arg(command, r'(?:-F|--file)[=\s]+["\']?([^\s"\']+)')
    if content and (p := _check_patterns_in_text(content, COMMIT_PATTERNS)):
        return f"Blocked: Self-attribution in commit file: {p}"

    return None


def check_gh_command(command: str) -> str | None:
    """Check if a gh command contains blocked attribution patterns."""
    if not re.search(r"\bgh\s+(pr|issue)\s+(create|edit|comment)", command):
        return None

    # Check command string itself
    if p := _check_patterns_in_text(command, GH_PATTERNS):
        return f"Blocked: Self-attribution pattern detected: {p}"

    # Check --body-file referenced file
    content = _read_file_arg(command, r'--body-file[=\s]+["\']?([^\s"\']+)')
    if content and (p := _check_patterns_in_text(content, GH_PATTERNS)):
        return f"Blocked: Self-attribution in body file: {p}"

    return None


def main() -> int:
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        # Can't parse input, allow by default
        return 0

    tool_input = input_data.get("tool_input", {})
    command = tool_input.get("command", "")

    if not command:
        return 0

    # Check for blocked patterns
    for checker in [check_git_commit, check_gh_command]:
        if error := checker(command):
            print(error, file=sys.stderr)
            return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
