#!/usr/bin/env zsh
# dhk: run hk commands in the dotfiles repo
emulate -L zsh
setopt localtraps

local hk_bin=""
if (( $+commands[hk] )); then
  hk_bin="${commands[hk]}"
elif (( $+commands[mise] )); then
  hk_bin="$(mise which hk 2>/dev/null)"
fi

if [[ -z "$hk_bin" ]]; then
  print -u2 "hk not found. Install tools with: mise install"
  return 127
fi

cd "$HOME" || return 1
export GIT_DIR="$HOME/git/dotfiles"
export GIT_WORK_TREE="$HOME"
export HK_STASH_UNTRACKED=false
"$hk_bin" "$@"
