#!/usr/bin/env zsh
# tmremind: set tmux reminder message
emulate -L zsh

if [[ $# -eq 0 ]]; then
  echo "Usage: tmremind <message>"
  return 1
fi

printf '%s\n' "$*" > "$HOME/.tmux-reminder"
echo "tmux reminder set"
