#!/usr/bin/env zsh
# nrsr: nixos-rebuild switch --rollback using $NIXOS_FLAKE (default: ~/.config/nix)
emulate -L zsh

sudo nixos-rebuild switch --flake "${NIXOS_FLAKE:-$HOME/.config/nix}" --rollback "$@"
